spring.application.name=Finguard
spring.datasource.url=jdbc:mysql://localhost:3306/finguard?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9091
file.upload-dir=./uploads/documents
# above code is the server-file-system location.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.error.include-message=always